=== NikitaSkorohodov/xmlWorcs/NikitaSkorohodovxml/news.dtd
<!ELEMENT channel (item+)>
<!ELEMENT item (title,description,link,guid,pubDate,author,category+,enclosure)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT guid (#PCDATA)>
<!ATTLIST guid isPermaLink NMTOKEN #FIXED "false"><!ELEMENT pubDate (#PCDATA)><!ELEMENT author (#PCDATA)><!ELEMENT category (#PCDATA)><!ATTLIST category domain CDATA #REQUIRED><!ELEMENT enclosure EMPTY><!ATTLIST enclosure url CDATA #REQUIRED><!ATTLIST enclosure length CDATA #FIXED ""><!ATTLIST enclosure type CDATA #FIXED "image/jpeg">

=== NikitaSkorohodov/xmlWorcs/NikitaSkorohodovxml/news.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE channel SYSTEM "news.dtd">
<?xml-model href="news.xsd"?>
<channel>
    <item>
    <title>HIINA JA USA PINGEVÄLI ⟩ Hiina matkis sõjaväeõppustel Taiwani sissepiiramist</title>
    <description>Taiwani ümbruses tuvastati 11 Hiina sõjalaeva ja 59 lennukit, teatas Taiwani kaitseministeerium ajal, kui Hiina jätkab kolmandat päeva sõjaväeõppusi Taiwani läheduses. </description>
    <link>https://pmo.ee/7750254</link>
    <guid isPermaLink="false">pm#7750254</guid>
    <pubDate>Mon, 10 Apr 2023 11:01:24 +0300</pubDate>
    <author>AFP/BNS</author>
    <category domain="https://maailm.postimees.ee">Maailm</category>
    <category domain="https://maailm.postimees.ee/section/5441">Regioonid</category>
    <category domain="https://maailm.postimees.ee/section/5743">Aasia</category>
    <enclosure url="https://f9.pmo.ee/LaTni_pSvXIIuGvY9oXTaIl9UQE=/480x270/filters:focal(221x175:2909x1943)/nginx/o/2023/04/10/15247734t1h9e0e.jpg" length="" type="image/jpeg"/>
    </item>
    <item>
    <title>VIDEO ⟩ Suveks vormi: viieminutiline treening, mis on jõukohane kõigile</title>
    <description>Health Insider avaldab 14 päeva kestva väljakutse raames iga päev ühe treeningvideo, mis on jõukohane kõigile ja sobib ideaalselt kodus treenimiseks. </description>
    <link>https://pmo.ee/7230685</link>
    <guid isPermaLink="false">pm#7230685</guid>
    <pubDate>Mon, 10 Apr 2023 11:00:00 +0300</pubDate>
    <author>PM Tervis</author>
    <category domain="https://tervis.postimees.ee">Tervis</category>
    <category domain="https://tervis.postimees.ee/section/2129">Toit ja trenn</category>
    <enclosure url="https://f10.pmo.ee/W7KGKXrWKei_3cuDirbVbGM1Tfs=/480x270/smart/nginx/o/2021/04/21/13740745t1hcc92.jpg" length="" type="image/jpeg"/>
    </item>
    <item>
    <title>Vanglateenistuse kriminaalhooldust asus juhtima Jako Salla</title>
    <description>Esmaspäevast töötab vanglateenistuse kriminaalhoolduse direktorina varem justiitsministeeriumis, prokuratuuris ja Ohvriabi juhina töötanud Jako Salla.</description>
    <link>https://pmo.ee/7750377</link>
    <guid isPermaLink="false">pm#7750377</guid>
    <pubDate>Mon, 10 Apr 2023 10:45:00 +0300</pubDate>
    <author>BNS</author>
    <category domain="https://www.postimees.ee">Postimees</category>
    <category domain="https://www.postimees.ee/section/128">Krimi</category>
    <enclosure url="https://f11.pmo.ee/M2kRNI8ptFY4KEp5U9nTmsovz4A=/480x270/smart/nginx/o/2022/05/13/14547898t1h8017.jpg" length="" type="image/jpeg"/>
    </item>
    <item>
    <title>GALERII ⟩ «Laula mu laulu» teises saates kõlasid Stig Rästa laulud</title>
    <description>Laupäeval, 8. aprillil oli Inspira kanali eetris «Laula mu laulu» selle hooaja teine saade, kus saates osalejad esitasid Stig Rästa laule. Vaata galeriid!</description>
    <link>https://pmo.ee/7750330</link>
    <guid isPermaLink="false">pm#7750330</guid>
    <pubDate>Mon, 10 Apr 2023 10:45:00 +0300</pubDate>
    <author>Elu24</author>
    <category domain="https://elu24.postimees.ee">Elu24</category>
    <category domain="https://elu24.postimees.ee/section/44">Pildinurk</category>
    <enclosure url="https://f11.pmo.ee/F9O-fEaY2FlHpnlxqMiIM1QBM2Q=/480x270/filters:focal(942x525:1052x727)/nginx/o/2023/04/10/15247480t1hb3af.jpg" length="" type="image/jpeg"/>
    </item>
    <item>
    <title>REISILEIUD ⟩ Põnev reis Tokyosse on sinust vaid 576 euro kaugusel</title>
    <description>Tänased reisileiud on pärit trip.ee lehelt. </description>
    <link>https://pmo.ee/7750327</link>
    <guid isPermaLink="false">pm#7750327</guid>
    <pubDate>Mon, 10 Apr 2023 10:45:00 +0300</pubDate>
    <author>Postimees Reis</author>
    <category domain="https://reis.postimees.ee">Reis</category>
    <enclosure url="https://f10.pmo.ee/GD_B0RKbZN3dIjZ_xG78WcwaJp4=/480x270/filters:focal(509x62:732x666)/nginx/o/2023/04/10/15247486t1hc28d.jpg" length="" type="image/jpeg"/>
    </item>
    <item>
    <title>Pealekasvav laskesuusatalent riputas 22-aastaselt püssi varna</title>
    <description>Saksamaa laskesuusatamise tulevikulootuseks peetud Luise Müller otsustas paljude jaoks ootamatult 22-aastaselt karjäärile joone alla tõmmata.</description>
    <link>https://pmo.ee/7750243</link>
    <guid isPermaLink="false">pm#7750243</guid>
    <pubDate>Mon, 10 Apr 2023 10:45:00 +0300</pubDate>
    <author>Toimetas Karl Juhkami</author>
    <category domain="https://sport.postimees.ee">Sport</category>
    <category domain="https://sport.postimees.ee/section/504">Talisport</category>
    <category domain="https://sport.postimees.ee/section/505">Laskesuusatamine</category>
    <enclosure url="https://f10.pmo.ee/aJV9t4RU2kZ4cvw8MeOtCVPX1xw=/480x270/filters:focal(221x44:427x175)/nginx/o/2023/04/10/15247308t1he51c.jpg" length="" type="image/jpeg"/>
    </item>
    <item>
    <title>TEADLASED ON RÄÄKINUD ⟩ See paljude lemmikjook võib pikendada eluiga</title>
    <description>Mõõdukas kohvi tarbimine aitab püsida tööülesannete kõrgusel ning pikendada ühtlasi ka sinu eluiga.</description>
    <link>https://pmo.ee/7534641</link>
    <guid isPermaLink="false">pm#7534641</guid>
    <pubDate>Mon, 10 Apr 2023 10:44:00 +0300</pubDate>
    <author>Kodu.postimees.ee</author>
    <category domain="https://kodu.postimees.ee">Kodu</category>
    <category domain="https://kodu.postimees.ee/section/5783">Toit</category>
    <enclosure url="https://f11.pmo.ee/e6rIkONhzT6huwW-zbjcdLudZWw=/480x270/filters:focal(138x724:927x1704)/nginx/o/2023/04/10/15247428t1h2de6.jpg" length="" type="image/jpeg"/>
    </item>
    <item>
    <title>Paneelmaja lifti mootoriruum hakkas kärssama ja jättis proua kinni</title>
    <description>Suurel reedel tuli päästjatel aidata Haaberstis üheksakordse kortermaja lifti kinni jäänud eakat naist. Häirekeskusesse helistanud ülemiste korruste naabrid olid tundnud ka kärsahaisu. </description>
    <link>https://pmo.ee/7750368</link>
    <guid isPermaLink="false">pm#7750368</guid>
    <pubDate>Mon, 10 Apr 2023 10:43:00 +0300</pubDate>
    <author>Postimees</author>
    <category domain="https://www.postimees.ee">Postimees</category>
    <category domain="https://www.postimees.ee/section/253">Tallinn</category>
    <enclosure url="https://f10.pmo.ee/emE9V7vAv7AB_7Tjf8noUj8Wy6o=/480x270/smart/nginx/o/2023/02/01/15112584t1he465.jpg" length="" type="image/jpeg"/>
    </item>
    <item>
    <title>Anne kanali ääres algavad tasuta välitrennid</title>
    <description>Tartu linn alustab 24. aprillil taas tasuta välitreeningutega täiskasvanutele. Treeningud toimuvad esmaspäeviti kell 18.00 – 19.30 Anne kanali äärsel välijõusaali platsil.</description>
    <link>https://pmo.ee/7750334</link>
    <guid isPermaLink="false">pm#7750334</guid>
    <pubDate>Mon, 10 Apr 2023 10:37:01 +0300</pubDate>
    <author>Egeli Raudmäe</author>
    <category domain="https://tartu.postimees.ee">Tartu Postimees</category>
    <enclosure url="https://f11.pmo.ee/X8kxUvskIngfRPkWsvXm_6bFeMY=/480x270/smart/nginx/o/2023/04/10/15247498t1hee2e.jpg" length="" type="image/jpeg"/>
    </item>
    <item>
    <title>Laupäeval põles ehitussoojak Vinni vallas</title>
    <description>Laupäeva õhtupoolikul kell 17.36 teatati päästeametile ehitussoojaku põlengust Vinni vallas Pajusti alevikus.</description>
    <link>https://pmo.ee/7750357</link>
    <guid isPermaLink="false">pm#7750357</guid>
    <pubDate>Mon, 10 Apr 2023 10:25:00 +0300</pubDate>
    <author>Andres Tohver</author>
    <category domain="https://virumaateataja.postimees.ee">Virumaa Teataja</category>
    <category domain="https://virumaateataja.postimees.ee/section/385">Uudised</category>
    <enclosure url="https://f12.pmo.ee/2Hq7aJrKw67TTlME0XG1aX505kI=/480x270/smart/nginx/o/2023/04/10/15247622t1hdde0.jpg" length="" type="image/jpeg"/>
    </item>
</channel>
